#!/bin/bash
# Credits: Joel Rodriguez
# Description: install dotfiles in $HOME folder
# Requires: 
# Use: ./install

# important resources
# https://www.cyberciti.biz/faq/find-command-exclude-ignore-files/

# anadir las carpetas y archivos a ser ignorados

#TODO
# fonts folder install
# wallpapers folder
# mozilla folder
# pip2.backup, reload file siempre
# pip3.backup, reload file siempre con cambios
# tmux plugins
# vim plugins install
# file de aplicaciones instaladas con apt-get, apt, dpkg

exclude_dirs=("./.git/*" "./personal/*")
exclude_files=("install" "install_dependencies" "README.md" "test" ".gitignore", ".editorconfig")
install_folder=$HOME/prueba_dotfiles
dir=$(pwd)

#crear los string de excluidos dir y files
base=""
base_dirs=""
for exclude_files in "${exclude_files[@]}";do
	base="${base} -name '${exclude_files}' -or"
done
for exclude_dirs in "${exclude_dirs[@]}";do
	base_dirs="${base_dirs} -path '${exclude_dirs}' -or"
done
exclude_files_string=$(echo $base | rev | cut -c4- | rev)
exclude_dirs_string=$(echo $base_dirs | rev | cut -c4- | rev)

tmp="find '.' -type f !  \( ${exclude_dirs_string} \)  ! \( ${exclude_files_string} \)  | tr '\n' ' '"
files=$(eval $tmp)
dotfiles=($files)

for dotfile in "${dotfiles[@]}";do
	dotfile_tmp=$(echo $dotfile | cut -c3-)
	base_name=$(basename $dotfile)
	dir_base=$(dirname "${dotfile}")
	dir_file=$(dirname "${dotfile}" | cut -c3-)
	if [[ $dir_base -ef . ]]; then
       ln -sf  $dir/$dotfile_tmp $install_folder/.${base_name}
	else
		if [ ! -d "$install_folder/.$dir_file" ]; then
	  		mkdir -p $install_folder/.${dir_file}
		fi
		ln -sf $dir/$dotfile_tmp $install_folder/.${dir_file}/${base_name}
	fi
done